title: "Skincare with Salmeen"
email: ""
description: "Professional Esthetician"
url: "https://www.skincarewithsalmeen.com"
github_username: salmeens
minimal_mistakes_skin: "dark"
search: true
copyright: "Skincare with Salmeen"
copyright_url: "https://www.skincarewithsalmeen.com"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/

timezone: America/Toronto

include:
  - _pages
  - googlef46b5fcb1c61719b.html

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name             : "Salmeen"
  avatar           : "/assets/images/salmeen.jpg"
  bio              : "Licensed Esthetician & Skincare Specialist"
  location         : "Toronto, Canada"
  email            : "info@skincarewithsalmeen.com"
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/skincarewithsalmeenbangla"
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://tiktok.com/@salmeenc"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/skincarewithsalmeenbangla"
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://tiktok.com/@salmeenc"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      header:
        overlay_color: "#000"
        overlay_filter: "0.5"
