# Site Settings
locale: "en-CA"
title: "Skincare with Salmeen"
logo: "/assets/images/logo.png"
email: "salmeen@skincarewithsalmeen.com"
description: "Licensed Esthetician"
url: "https://www.skincarewithsalmeen.com"
baseurl: ""
repository: "salmeens/salmeens.github.io"
copyright: "Skincare with Salmeen"
copyright_url: "https://www.skincarewithsalmeen.com"

# Site Configuration
minimal_mistakes_skin: "custom"
search: false
search_full_content: false
atom_feed:
  hide: true

# SEO Related
facebook:
  username: "skincarewithsalmeenbangla"
og_image: "/assets/images/logo.png"
social:
  links:
    - "https://www.youtube.com/@skincarewithsalmeen"
    - "https://www.tiktok.com/@salmeen_c?_t=ZM-8w0ZgmfpGzv&_r=1"
    - "https://facebook.com/skincarewithsalmeenbangla"

# Analytics
# TODO: Google Analytics Setup
# 1. Get GA4 tracking ID from Google Analytics (format: G-XXXXXXXXXX)
# 2. Change provider: false to provider: "google"
# 3. Uncomment and add tracking_id below
analytics:
  provider: false
  google:
    tracking_id: # "G-XXXXXXXXXX"
    anonymize_ip: true # false by default

# Site Author
author:
  name: "Salmeen"
  avatar: "/assets/images/salmeen-bio.jpg"
  bio: >
    Licensed Esthetician &#124; Skincare Educator &#124; Content Creator
  location: "Toronto, ON, Canada"
  email: "salmeen@skincarewithsalmeen.com"
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@skincarewithsalmeen"
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://www.tiktok.com/@salmeen_c?_t=ZM-8w0ZgmfpGzv&_r=1"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/skincarewithsalmeenbangla"

# Footer
footer:
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@skincarewithsalmeen"
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://www.tiktok.com/@salmeen_c?_t=ZM-8w0ZgmfpGzv&_r=1"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/skincarewithsalmeenbangla"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/Toronto

# Sass
sass:
  style: compressed
  sourcemap: never

# Outputting
include:
  - _pages
  - favicon.ico
  - assets/images/favicon
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /test
  - /docs
  - /example

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      header:
        overlay_color: "#000"
        overlay_filter: "0.5"
